#!/usr/bin/env python
from __future__ import annotations
import argparse
from pathlib import Path
import pandas as pd

TEMPLATE = """# Demo Narrative — {model} / {param_id}

## 1) What this demo is
- **Model:** {model}
- **Param ID:** {param_id}
- **Representative run:** `{run_id}`
- **Case ID:** `{case_id}`
- **Regime label:** **{regime_label}**
- **Status:** **{status}**

## 2) What we can claim (audit-safe)
- **Closed-mode Lyapunov:** Ω(t) is non-increasing (strict solver gate).
- **Produced change over horizon:** ΔΩ = Ω(0) − Ω(T) = **{DeltaOmega}** (≥ 0 in closed mode).

## 3) Minimal interpretation (value-first, optional layer)
Operational mapping (derived, not an extra axiom):
- **Conflict/Resistance** ≈ Ω(t)  (higher Ω = more “tension” in the configuration)
- **Produced value** over the run ≈ ΔΩ  (how much “tension” is reduced / released)

This is a *measurement interpretation* only. It does not require metaphysical “meaning”.

## 4) What to look at
Plots (generated from artifacts):
- Ω(t): `{omega_plot}`
- dΩ(t): `{domega_plot}`
- range_C(t): `{rangeC_plot}`
- range_I(t): `{rangeI_plot}`

## 5) Notes for development
- backtracks_total: {backtracks_total}
- If backtracks_total is large but still PASS: treat as stiffness boundary marker.
- If regime label flips under dt/2 or grid*2: treat as boundary/transition zone.

## 6) Reproduction
Folder (packed):
`{packed_run_dir}`

Re-run via harness with the same config (config.json inside the folder).

---
Generated by `make_demo_narratives.py`
"""

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--demo_pack_index", required=True, help="demo_pack/demo_pack_index.csv")
    ap.add_argument("--out_dir", default="", help="output narratives folder (default: <demo_pack>/NARRATIVES)")
    args = ap.parse_args()

    idx_path = Path(args.demo_pack_index)
    demo_pack_root = idx_path.parent
    out_dir = Path(args.out_dir) if args.out_dir else (demo_pack_root / "NARRATIVES")
    out_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(idx_path)
    if len(df) == 0:
        (out_dir / "README.md").write_text("# Demo Narratives\n\n_No demos found in index._\n", encoding="utf-8")
        print(f"No demos. Wrote {out_dir/'README.md'}")
        return

    readme_lines = ["# Demo Narratives", ""]
    for _, r in df.iterrows():
        model = str(r.get("model",""))
        pid = str(r.get("param_id",""))
        run_id = str(r.get("run_id",""))
        case_id = str(r.get("case_id",""))
        status = str(r.get("status",""))
        regime_label = str(r.get("regime_label",""))
        DeltaOmega = r.get("DeltaOmega","")
        backtracks_total = r.get("backtracks_total","")
        packed_run_dir = str(r.get("packed_run_dir",""))
        plots_dir = Path(packed_run_dir) / "plots"

        omega_plot = str(plots_dir / "omega_t.png")
        domega_plot = str(plots_dir / "domega_t.png")
        rangeC_plot = str(plots_dir / "range_C_t.png")
        rangeI_plot = str(plots_dir / "range_I_t.png")

        md = TEMPLATE.format(
            model=model, param_id=pid, run_id=run_id, case_id=case_id, status=status,
            regime_label=regime_label, DeltaOmega=DeltaOmega, backtracks_total=backtracks_total,
            packed_run_dir=packed_run_dir, omega_plot=omega_plot, domega_plot=domega_plot,
            rangeC_plot=rangeC_plot, rangeI_plot=rangeI_plot
        )

        out_path = out_dir / f"{model}__{pid}.md"
        out_path.write_text(md, encoding="utf-8")
        readme_lines.append(f"- {model} / {pid}: `{out_path.name}`")

    (out_dir / "README.md").write_text("\n".join(readme_lines) + "\n", encoding="utf-8")
    print(f"Wrote narratives to {out_dir} ({len(df)} files)")

if __name__ == "__main__":
    main()
