"""
UET Documentation Auditor
=========================
Systematically scans the 'research_uet/topics' directory to ensure:
1. Every Code File (.py) has a corresponding Analysis Report (.md) in Doc/.
2. Every Report meets the "Paper-Ready" standard (Executive Summary, Logic, Results).

Output:
- Generates a 'Documentation_Gap_Report.md' listing missing files.
"""

import os
import sys
from pathlib import Path
from typing import Dict, List, Tuple
import re

# Standardize Headers
REQUIRED_HEADERS = [
    "Executive Summary",
    "Theoretical Framework",
    "Implementation",
    "Validation & Results",
    "Discussion",
    "Conclusion",
]


def scan_topics(root_dir: Path) -> Dict[str, Dict]:
    """Scans all topics and maps Code -> Doc status."""
    topics_dir = root_dir / "research_uet" / "topics"
    audit_map = {}

    for topic_path in topics_dir.iterdir():
        if not topic_path.is_dir() or not topic_path.name[0].isdigit():
            continue

        topic_name = topic_path.name
        code_dir = topic_path / "Code"
        doc_dir = topic_path / "Doc"

        if not code_dir.exists():
            continue

        # 1. Collect Code Files
        code_files = []
        for r, _, f in os.walk(code_dir):
            for file in f:
                if file.endswith(".py") and file != "__init__.py":
                    rel_path = Path(r) / file
                    code_files.append(rel_path)

        # 2. Collect Doc Files
        doc_files = []
        if doc_dir.exists():
            for r, _, f in os.walk(doc_dir):
                for file in f:
                    if file.endswith(".md"):
                        doc_files.append(Path(r) / file)

        # 3. Map Coverage
        file_status = {}
        for code_file in code_files:
            coverage = check_coverage(code_file, doc_files)
            file_status[code_file.name] = coverage

        audit_map[topic_name] = file_status

    return audit_map


def check_coverage(code_file: Path, doc_files: List[Path]) -> str:
    """Checks if a code file is covered by any doc file."""
    # Strategy 1: Direct Link (File name in Doc content)
    # Strategy 2: Naming Convention (Engine_Galaxy -> ANALYSIS_01_Engine)

    status = "MISSING"

    # Check 1: Name Logic
    base_name = code_file.name
    pillar = code_file.parent.name  # 01_Engine, 02_Proof

    # Heuristic: Does a doc exist for this pillar?
    pillar_doc_exists = False
    for doc in doc_files:
        if pillar in doc.name or ("Engine" in base_name and "01_Engine" in doc.name):
            pillar_doc_exists = True
            # Deep check: Does the doc mention the file?
            try:
                content = doc.read_text(encoding="utf-8")
                if base_name in content:
                    return "COVERED"  # Perfect Match
                else:
                    status = "UNLINKED"  # Doc exists but file not mentioned
            except:
                pass

    if status == "UNLINKED":
        return "PARTIAL (Pillar Doc exists, File not named)"

    return status


def generate_report(audit_map: Dict[str, Dict]):
    """Prints the Gap Analysis."""
    print("# 📋 UET Documentation Gap Analysis")
    print("Generated by: audit_documentation_coverage.py\n")

    total_files = 0
    missing_count = 0

    for topic, files in sorted(audit_map.items()):
        print(f"## {topic}")
        missing_in_topic = 0
        for fname, status in files.items():
            total_files += 1
            if status == "MISSING":
                missing_count += 1
                missing_in_topic += 1
                print(f"- [ ] {fname} -> 🔴 {status}")
            elif "PARTIAL" in status:
                print(f"- [/] {fname} -> 🟡 {status}")
            else:
                # print(f"- [x] {fname} -> 🟢 {status}") # Omit covered to save space
                pass

        if missing_in_topic == 0:
            print("  ✅ All files covered.")
        print("")

    coverage_pct = ((total_files - missing_count) / total_files) * 100
    print("-" * 50)
    print(f"Total Code Files: {total_files}")
    print(f"Missing Reports:  {missing_count}")
    print(f"Coverage Score:   {coverage_pct:.1f}%")


if __name__ == "__main__":
    current = Path(__file__).resolve().parent.parent
    if (current / "research_uet").exists():
        scan_root = current
    else:
        scan_root = Path(os.getcwd())

    audit_map = scan_topics(scan_root)
    generate_report(audit_map)
